### ISSUE TITLE
AssertionError: size of input tensor and input format are different

### ISSUE THREAD

**Issue by magemoumou** [vasgaowei/pytorch_MELM#3]
With a series of file index mismatch problems in your code-file "train_faster_rcnn.sh" being debugged.
I successfully got to the following running process:
'"
+ python ./tools/trainval_net.py --weight data/imagenet_weights/vgg16.pth --imdb voc_2007_trainval --imdbval voc_2007_test --iters 100000 --cfg experiments/cfgs/vgg16.yml --net vgg16 --set ANCHOR_SCALES '[8,16,32]' ANCHOR_RATIOS '[0.5,1,2]' TRAIN.STEPSIZE '[50000]'
'"
But a new problem just comes up:
"'
(omit)
Solving...
Loading initial model weights from data/imagenet_weights/vgg16.pth
Loaded.
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 130, in <module>
    max_iters=args.max_iters)
  File "/data/pytorch_MELM/tools/../lib/model/train_val.py", line 356, in train_net
    sw.train_model(max_iters)
  File "/data/pytorch_MELM/tools/../lib/model/train_val.py", line 264, in train_model
    self.net.train_step_with_summary(blobs, self.optimizer)
  File "/data/pytorch_MELM/tools/../lib/nets/network.py", line 724, in train_step_with_summary
    summary = self._run_summary_op()
  File "/data/pytorch_MELM/tools/../lib/nets/network.py", line 534, in _run_summary_op
    summaries.append(self._add_gt_image_summary())
  File "/data/pytorch_MELM/tools/../lib/nets/network.py", line 67, in _add_gt_image_summary
    return tb.summary.image('GROUND_TRUTH', image[0].astype('float32').swapaxes(1,0).swapaxes(2,0)/255.0)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/summary.py", line 211, in image
    tensor = convert_to_HWC(tensor, dataformats)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/utils.py", line 98, in convert_to_HWC
    assert(len(tensor.shape) == len(input_format)), "size of input tensor and input format are different"
AssertionError: size of input tensor and input format are different
"'
I don't know if it is because I changed the context in the "train_faster_rcnn.sh".
Whatever it just doesn't work and I am a noob don;t know how to fix it.
Thanks for all have you done and look forward to your early reply to this problem.

**Comment by vasgaowei** [comment]
I'm sorry, i will update a new vision to fix many existed problems. And as for the problem you met, i suggest use version tensorboardX 1.4 and tensorboard 1.11.0.

**Comment by magemoumou** [comment]
It does work!
Thanks for your help.

**Comment by ltc576935585** [comment]
can you tell me your tensorflow version？
